server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-connections: 2000
    max-threads:  2000

spring:
  thymeleaf:
    cache: false
    #非严格模式的HTML语法检查
    mode: LEGACYHTML5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
    type: com.alibaba.druid.pool.DruidDataSource
resources:
  static-locations:  file:f://upload/
http:
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
  type-aliases-package: top.putongren.dxcblog.model


logging:
  level:
    top.putongren.dxcblog.dao: debug
